### ISSUE TITLE
Question about Cifar10 RocAUC

### ISSUE THREAD

**Issue by Donkdot** [rohban-lab/Knowledge_Distillation_AD#11]
Hello! The RocAUC of cifar10 is only about 78% after 201 epoch. Is there anything wrong with my config setting?

**Comment by Donkdot** [comment]
![微信图片_20220611180441](https://user-images.githubusercontent.com/52710974/173183371-d641091b-1ca2-466d-b176-368fa26da41b.png)

**Comment by hustCYQ** [comment]
Have you known where to modify to improve the RocAUC? Could you tell me, please?

**Comment by willyfh** [comment]
@hhlsygmz could you explain why did you close this issue? did you figure out the problem?
