### ISSUE TITLE
About the results of anomaly localization

### ISSUE THREAD

**Issue by wangyf256** [rohban-lab/Knowledge_Distillation_AD#2]
Hello, thank you for sharing. I am very interested in your work and ran this code on MVTec without modifying any settings (except those MVTec specific parameters). The results obtained are far from your paper. Maybe I haven’t noticed some details, but I don’t have any clues either. I hope you can give me some suggestions.

“——” represent my results
![kd](https://user-images.githubusercontent.com/37993856/115136594-5264ce80-a053-11eb-896a-92c3898190e6.png)

**Comment by SMSD75** [comment]
Thank you for your interest in our research. We will review the code and come back to you soon.

**Comment by Niousha12** [comment]
Thanks for your interest.
I have reviewed the code, and unfortunately, there was a minor bug in dataloader.py file. Shuffling the test dataset will corrupt the corresponding relationship between ground truth and test data.
I have fixed the problem by changing lines 110 and 130 to '' shuffle=False ". You can change it yourself or push the last commit from the repository.
Also, to reproduce the result in localization you should remove the "good" folder from the "{mvtec_class_name}/test/" folder.
I have also attached my config file, so you can compare it with yours.

[config.zip](https://github.com/rohban-lab/Knowledge_Distillation_AD/files/6336033/config.zip)

**Comment by wangyf256** [comment]
Thank you for your prompt answer, it is indeed no problem after modification.
