### ISSUE TITLE
Config and Results

### ISSUE THREAD

**Issue by ArashLagzian** [rohban-lab/Knowledge_Distillation_AD#8]
Hi,

How can I reach the results in table 2 **for each class** in mnist, fashion mnist, and cifar10 datasets? for example class "0"
what config is needed?

Thanks for your great work.

**Comment by SMSD75** [comment]
You can use the default configurations existing in the codes. They are all reproducible.

**Comment by ArashLagzian** [comment]
Hi,

Can I ask you about config of Retina and OCT Datasets?

Thanks

**Comment by SMSD75** [comment]
Hi, 

All the configs exist in the paper.

Bests.
